steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-west1-docker.pkg.dev/pdg-project-406720/pdg-artifact-registry/rts-train:v2
      - -f
      - computing/Dockerfile.train
      - .
images:
  - us-west1-docker.pkg.dev/pdg-project-406720/pdg-artifact-registry/rts-train:v2
timeout: 1800s
