"""Generate the GEE Code Editor QC-rating app from the QC sample (Phase 3).

Embeds every sampled polygon (WGS84 outline + centroid + its chip COG URIs)
into `post-inference/ee_qc_rater.js`. In the Code Editor the app steps through
the polygons one at a time — Planet RGB chips via `ee.Image.loadGeoTIFF`
(US-CENTRAL1 mirror bucket, same constraint as `ee_south_viewer.js`), outline
overlaid — and the user clicks **RTS / false / unsure**. Verdicts export as a
CSV Task (rts_id, qc_verdict) for `scripts/score_qc_ratings.py`.

Usage:
    python scripts/build_ee_qc_rater.py \
        --sample /outputs/.../qc_sample.gpkg \
        --out post-inference/ee_qc_rater.js
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

import geopandas as gpd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from utils.logging import setup_logging  # noqa: E402

logger = logging.getLogger(__name__)

DEFAULT_CHIP_PREFIX = ("gs://rts-mapping-v2-usc1/ee_mirror/2025q3_south/"
                       "products/qc_chips/rgb_chips/")

_TEMPLATE = """\
// GEE Code Editor QC rater — GENERATED by scripts/build_ee_qc_rater.py; do not hand-edit.
// Rate each polygon RTS / false / unsure; click EXPORT when done, run the Task,
// and feed the CSV to scripts/score_qc_ratings.py.
// Chips read via loadGeoTIFF from the US-CENTRAL1 mirror (see ee_south_viewer.js).

var FEATURES = __FEATURES__;

var verdicts = {};
var idx = 0;

var label = ui.Label('', {fontWeight: 'bold'});
var meta = ui.Label('');
var done = ui.Label('');

function chipImage(f) {
  var imgs = f.chips.map(function (uri) { return ee.Image.loadGeoTIFF(uri); });
  return ee.ImageCollection(imgs).mosaic();
}

function show(i) {
  idx = Math.max(0, Math.min(i, FEATURES.length - 1));
  var f = FEATURES[idx];
  Map.layers().reset();
  Map.addLayer(chipImage(f), {min: 0, max: 255}, 'Planet RGB chips');  // chips are uint8 visual RGB
  var ring = ee.Geometry.Polygon([f.ring]);
  Map.addLayer(ee.FeatureCollection([ee.Feature(ring)]).style(
      {color: 'ff0000', fillColor: '00000000', width: 2}), {}, 'candidate');
  Map.centerObject(ring, 15);
  label.setValue((idx + 1) + ' / ' + FEATURES.length + '   [id ' + f.id + ']');
  meta.setValue('tier=' + f.cls + '   area=' + Math.round(f.area_m2) +
                ' m2   verdict: ' + (verdicts[f.id] || '-'));
  done.setValue(Object.keys(verdicts).length + ' rated');
}

function rate(v) {
  verdicts[FEATURES[idx].id] = v;
  show(idx + 1);
}

function csvText() {
  var lines = ['rts_id,qc_verdict'];
  FEATURES.forEach(function (f) {
    if (verdicts[f.id]) { lines.push(f.id + ',' + verdicts[f.id]); }
  });
  return lines.join('\\n');
}

function exportCsv() {
  // primary: print to console — copy/paste into a .csv, no server involved
  // (Export.table intermittently 500s on task submission)
  print('--- copy everything between the markers into qc_ratings.csv ---');
  print(csvText());
  print('--- end ---');
  // secondary: a Drive export task, if the service cooperates
  var feats = FEATURES.filter(function (f) { return verdicts[f.id]; })
      .map(function (f) {
        return ee.Feature(null, {rts_id: f.id, qc_verdict: verdicts[f.id]});
      });
  Export.table.toDrive({collection: ee.FeatureCollection(feats),
                        description: 'qc_ratings',
                        fileFormat: 'CSV',
                        selectors: ['rts_id', 'qc_verdict']});
  print('Also created a Drive export task (' + feats.length +
        ' ratings) — optional, console CSV above is authoritative.');
}

var panel = ui.Panel({style: {width: '260px'}});
panel.add(ui.Label('RTS QC rater', {fontWeight: 'bold', fontSize: '16px'}));
panel.add(label);
panel.add(meta);
panel.add(ui.Button('RTS', function () { rate('rts'); }));
panel.add(ui.Button('false', function () { rate('false'); }));
panel.add(ui.Button('unsure', function () { rate('unsure'); }));
panel.add(ui.Button('◀ prev', function () { show(idx - 1); }));
panel.add(ui.Button('skip ▶', function () { show(idx + 1); }));
panel.add(ui.Button('EXPORT ratings CSV', exportCsv));
panel.add(done);
ui.root.insert(0, panel);
show(0);
"""


def build_rater(sample_gpkg: str, out_js: str,
                chip_prefix: str = DEFAULT_CHIP_PREFIX) -> None:
    """Embed the sample into the rater template and write the JS."""
    gdf = gpd.read_file(sample_gpkg).to_crs("EPSG:4326")
    feats = []
    for _, r in gdf.iterrows():
        geom = r.geometry
        if geom.geom_type == "MultiPolygon":  # seam-dissolved: outline the largest part
            geom = max(geom.geoms, key=lambda g: g.area)
        ring = [[round(x, 6), round(y, 6)]
                for x, y in geom.exterior.coords]
        chips = [f"{chip_prefix}{t}.tif"
                 for t in str(r["tile_ids"]).split(",") if t]
        feats.append(dict(id=int(r["rts_id"]), cls=str(r["conf_class"]),
                          area_m2=float(r["area_m2"]), ring=ring, chips=chips))
    js = _TEMPLATE.replace("__FEATURES__", json.dumps(feats))
    Path(out_js).write_text(js)
    logger.info("wrote %s (%d features)", out_js, len(feats))


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--sample", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--chip-prefix", default=DEFAULT_CHIP_PREFIX)
    args = p.parse_args()
    setup_logging()
    build_rater(args.sample, args.out, args.chip_prefix)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
